- examples/add.js
- examples/cat.js
- examples/ls.js
- examples/version.js
- index.js
- package.json
I hope i'm not pissing anyone off too bad here.
> add linting

- index.js
- package.json
Just the fix that tperson posted about.
Don't want to keep this around broken, published it to npm as well.
> release version 1.1.4

- .travis.yml
Adding Travis (in addition to Circle CI), so we can try both side by side.
> CI: add basic Travis config

- package.json
(Don't require that it be globally installed)
> Look for "standard" package in node_modules

- package.json
- test/test.js
bumped ipfsd-ctl version
also fixes #26
> make tests pass

- README.md
License: MIT
Signed-off-by: Jason Carver <ut96caarrs@snkmail.com>
> readme: add CORS note and module init

- package.json
dependency for the build script
> add dependancy on brfs

- README.md
Thanks to https://github.com/ipfs/node-ipfs-api/issues/57#issuecomment-140659299 :)
> Add circle CI badge

- README.md
> Edited for readbility, linguist

- README.md
- package.json
- test/tests.js
this updates some tests. however, the dht test is now failing and i cannot fix it. @whyrusleeping what changed?
> update tests to run against 0.3.9

- README.md
all other changes are whitespace only...
> Add travis CI badge to Readme

- src/request-api.js
Ref https://github.com/ipfs/go-ipfs/issues/1970
> fix: Handle non json formatted errors.

- src/get-files-stream.js
Depends on https://github.com/jbenet/node-vinyl-multipart-stream/pull/3
> Switch to flat files stream

- README.md
Avoid creating confusion - https://github.com/ipfs/js-ipfs-api/pull/322
@RichardLitt wanna review?
> add more info about testing and where tests live

- package.json
- src/api/swarm.js
Ref https://github.com/ipfs/interface-ipfs-core/pull/73
> feat(swarm): make interface-ipfs-core compliant

- src/api/block.js
instead of just using the multihash, use the cid encoding
> block.get - use cid.toBaseEncodedString

- src/files/add.js
Added additional option implementation for files/add 
`no-hash`
`pin`
I'm currently using both and they were tested
> add flags to files/add

- README.md
> docs: key api links

- src/key/gen.js
- src/key/import.js
- src/key/list.js
- src/key/rename.js
- src/key/rm.js
Ref.: https://github.com/ipfs/interface-ipfs-core/pull/192
> Normalize KEY API

- src/name/publish.js
- src/name/resolve.js
Ref.: ipfs/interface-ipfs-core#190
> Normalize NAME API

- src/files/ls.js
> fix: exception when dir is empty

- README.md
- package.json
- src/files/flush.js
- src/files/read.js
- src/repo/stat.js
- src/repo/version.js
- src/stats/repo.js
- test/files.spec.js
- test/interface/repo.spec.js
- test/interface/stats.spec.js
- test/repo.spec.js
Ref.: https://github.com/ipfs/interface-ipfs-core/pull/208. 
- tests: STAT spec
- fix(breaking change): REPO spec
- feat(breaking change): FILES spec: stream to value on files read
> breaking change: stats spec, spec repo, stream to value on files read

- src/util/url-add.js
- test/util.spec.js
Fixed error handling in `addFromURL` function.
> fix: handle request errors in addFromURL

- README.md
* Removes `>` and `$` prefix from code snippets for easier copy/paste
* Documents minified CDN version
* Adds missing syntax highlighting to code blocks
* Upgrades "interface-ipfs-core compatible" badge
* API fixes/changes
* Fixes links
* Adds missing API functions
* Standardizes optional arg syntax (square brackets for each arg)
* Orders API functions alphabetically
* Fixes a few typos
> docs: README fixes and improvements

- package.json
- src/resolve.js
- src/utils/load-commands.js
- test/interface.spec.js
Just being super careful not to accidentally remove the commit in https://github.com/ipfs/js-ipfs-api/pull/794
> feat: add resolve cmd

- package.json
> fix: add bl module to package dependencies (#853)

- package.json
- src/ping.js
https://github.com/ipfs/interface-ipfs-core/pull/386
> fix: make ping not mix errors with responses

- examples/name-api/index.js
- examples/name-api/package-lock.json
- examples/name-api/package.json
Updates deps and fixes example code!
> docs: update name-api example

- .travis.yml
Windows cannot have secrets (temporarily).
> fix: windows travis build

- examples/upload-file-via-browser/package.json
Update to latest Babel fixed ze problem.
> Fix: Babel error in upload-file-via-browser example #968

- maintainer.json
In preparation for https://github.com/ipfs/team-mgmt/pull/822
> docs: add maintainer.json

- .travis.yml
See https://github.com/ipfs/aegir/issues/345
> chore: remove commitlint from check stage in CI

- test/interface.spec.js
Saves 1 minute running them locally.
> chore: use test profile for swarm tests

- src/utils/send-files-stream.js
Needed by/depends on https://github.com/ipfs/js-ipfs/pull/2384
> feat: expose pin and preload arguments

- .travis.yml
Test on Node.js 12 and also utilise cache.
> chore: update windows Travis config

- package.json
> chore(package): update nock to version 11.3.2

- package.json
Depend on form-data ^2.5.1
Fixes #1099
> Add dependency for form-data 

- package.json
- src/dag/put.js
- src/object/get.js
- test/dag.spec.js
Depends on https://github.com/ipfs/interface-js-ipfs-core/pull/532
> chore: update ipld-dag-pb to the latest version

- src/add/index.js
> fix: expose preload argument

- package.json
closes https://github.com/ipfs/js-ipfs-http-client/issues/1126
> chore(package): update aegir to version 20.4.1

- package.json
closes https://github.com/ipfs/js-ipfs-http-client/issues/1125
> chore(package): update nock to version 11.4.0

- package.json
> chore(package): update it-glob to version 0.0.6

- package.json
- test/constructor.spec.js
- test/node/swarm.js
This reverts commit 9b1589c23946ace07483e5004d35880114bde729.
> revert: chore: update multiaddr to version 7.2.0 (#1136)

- README.md
I'm assuming that's what it was supposed to be.
> Change "IPN" to "IPNS" in README
