- index.js
As of node v0.12.0 (and v0.11.x), the http client uses `setHeader` on
each header key, this means if we have a key with an `undefined` or
`null` value it will try to set the header value, and not just skip it,
or use the default.
This update defaults us to `application/json`.
> 'name' and 'value' are required for setHeader().

- index.js
This add the ability to pass an opts object into `pin.add` and
`pin.remove` so the recursive option can be used.
Example:
```javascript
ipfs.pin.remove(<hash>, {r:true}, console.log);
```
Addresses #9
>  Implement opts into pin remove/add for recursive

- README.md
These code blocks are not literally json, so they get "invalid"-ish syntax highlighting, eg on the npm site & github.
> Remove json type from code blocks

- index.js
- multipartdir.js
- package.json
- test/test.js
This PR adds stream support for any command send data through the `files` argument of send. It addresses issue #4 and #3. 
Appropriate values for any `files` argument are streams, vinyl files, or buffers. Any stream or buffer will be converted to a vinyl file with the `cwd`, `base`, and `path` set to `/`, which basically is just an unnamed file.
The base of any filename is the relative pathing from the vinyl file `base`.
Wrapped files in a directory
-----------------------------------
```javascript
files.push(new File({
base: '/',
path: '/base/dir/hello.txt',
contents: new Buffer("world")
}))
files.push(new File({
base: '/',
path: '/base/dir/ipfs.txt',
contents: new Buffer("is cool")
}))
files.push(new File({
base: '/',
path: '/base/readme.md',
contents: new Buffer("wow")
})) …
```
> Add streams and directory building

- .travis.yml
- package.json
This updates the `ipfsd-ctl` package to make it use the shipped go-ipfs binary instead of looking for a local install.
Closes #24 after merge.
> Update the ipfsd-ctl package 

- index.js
- package.json
Vinyl complained about content not being a Buffer when browserified, thus breaking ipfs.add.
> make vinyl play nice with browserify

- examples/add.js
- index.js
- multipartdir.js
- package.json
- test/test.js
+ a test
the tests should be cleaned up a bit.
> add path support

- package.json
Otherwise:
webui/apps/connections$ browserify -t reactify index.jsx
Error: Cannot find module 'brfs' from '/home/krl/unison/work/ipfs/webui/apps/connections/node_modules/ipfs-web-app/node_modules/ipfs-api'
> Make brfs a non-dev-dependency

- package.json
- src/get-files-stream.js
commit b9e5313ab3e8064eba3551604f2974b33ce8e4af
Author: Juan Batiz-Benet <juan@benet.ai>
Date:   Fri Aug 14 22:57:26 2015 +0200
more vinyl fun: use thing that look like streams too
- cleaner file construction logic
- use thing that look like streams too
commit 76068f440b9c9383da72ade8b5ab2aac6dce121d
Author: Juan Batiz-Benet <juan@benet.ai>
Date:   Fri Aug 14 20:31:03 2015 +0200
use vinyl-fs-browser instead
> more vinyl fun

- src/index.js
If host is unset, and we're in the browser, use the window.location.host to auto-configure the api.
> autoconfigure in browser

- src/index.js
In order to make add work in the browser with the standalone browser, we need to access the Buffer object, it seems importing the browser-buffer as standalone trips up vinyl somehow.
This is not ideal, but unless we can find a way to make adding files from buffers really portable, it seems ok.
The three cases are:
* node, just works
* browserify, works
* standalone module in browser, not without exposing browserifys Buffer
> expose Buffer

- src/index.js
Change conditional to not try to access the `window` object (which throws error when `window` doesn't exist), instead we check the `typeof` so it doesn't crash if `window` is not defined.
We can also safely assume that `window.location` exists if `window` exists.
This closes issue #62
> Correctly detect browser vs node environment

- test/tests.js
this PR adds a quick check on the version output and prints out the version number (to show what version we're testing against. useful to test new versions)
> test: check + print version

- .eslintrc
- package.json
- src/get-files-stream.js
- src/request-api.js
- test/tests.js
So I have gotten superagent to work finally. But I sadly can not suggest to merge this. The reason being that the superagent browser part is much worse than the node part. 
My general feeling is still that we should not use `http.request` directly but rather do some research into what request modules are out there and do a good job of what we need them to do in the browser as well as in node.
> [discuss] Switch to superagent instead of raw http.request

- src/request-api.js
- test/tests.js
https://github.com/ipfs/js-ipfs-api/pull/92 introduced a bug where in Node.js, the result no longer comes as a stream. This happened because the .cat test was not properly differentiating between node and browser execution.
This PR is a WIP, the test is now checking correctly the behaviour.
> .cat is not returning a stream anymore

- circle.yml
Use latest stable node version on Circle CI.  Fixes the build.
> circle config

- .travis.yml
I suggest we test under node 4 and 5, and also stable, so when new node versions come out, we would be alerted by a broken build if tests failed there.
Thoughts @diasdavid @Dignifiedquire @VictorBjelkholm?
> test under multiple node versions

- tasks/build.js
> fix(build): Export ipfsApi global in browser build

- src/index.js
- src/request-api.js
- test/tests.js
> feat: Add urls directly.

- src/request-api.js
- tasks/daemons.js
- test/tests.js
Goal: Fix #76 still not there though..
When https://github.com/ipfs/go-ipfs/issues/1979 is merged we can remove the config settings in the daemon setup
> Header work

- package.json
- src/index.js
- test/tests.js
Works in node, will work in the browser with #128
> feat: Fix log/tail for 0.3.9

- package.json
- src/request-api.js
- test/tests.js
I was suspecting that something could be weird when adding big files and it seems I was right to have my suspicion (context https://botbot.me/freenode/ipfs/2015-11-21/?msg=54623933&page=6), however, I might be missing something, please review.
It seems that when cat'ing a big file, the parsing chunks one by one breaks the final file:
https://github.com/ipfs/js-ipfs-api/blob/master/src/request-api.js#L35-L46
> WIP: add and cat big file test (failing)

- package.json
- src/api/dht.js
- test/.eslintrc
- test/api/add.spec.js
- test/api/block.spec.js
- test/api/cat.spec.js
- test/api/commands.spec.js
- test/api/config.spec.js
- test/api/dht.spec.js
- test/api/diag.spec.js
- test/api/id.spec.js
- test/api/index.spec.js
- test/api/log.spec.js
- test/api/name.spec.js
- test/api/object.spec.js
- test/api/pin.spec.js
- test/api/ping.spec.js
- test/api/refs.spec.js
- test/api/swarm.spec.js
- test/api/version.spec.js
- test/constructor.spec.js
- test/setup.js
> Replace assert with chai

- src/load-commands.js
Webpack's `require.context` is transpiled only if ipfs-api is loaded or bundled
using webpack. This broke modules that require ipfs-api and use browserify or
other bundlers (such as webui)
Fixes ipfs/js-ipfs-api#159 by using individual requires. I opted for this because IMO maintaining a list of requires is less headache than dealing with the complexities of directory walking in different runtime contexts (browser, node, webpack, browserify, etc.)
> Replace `require.context` with individual requires.

- src/request-api.js
- test/request-api.spec.js
> Exclude port from path if `config.port` not set.

- package.json
- src/get-files-stream.js
- src/load-commands.js
- src/request-api.js
- test/api/add.spec.js
- test/api/files.spec.js
- test/setup.js
vinyl fs is gone!!!!
Minified version is about 100k less in size
> Working and passing

- test/api/ls.spec.js
Based on the work in #150.
Closes #150.
> test(ls): Add tests

- src/api/id.js
I renamed the parameter so it doesn't collide
Related to #124
> Fixes #124 (Cannot declare a parameter named 'mask' as it shadows the name of a strict mode function)

- .travis.yml
- README.md
- src/api/dht.js
- src/api/log.js
- src/api/ping.js
- src/request-api.js
- test/api/add.spec.js
- test/api/block.spec.js
- test/api/cat.spec.js
- test/api/commands.spec.js
- test/api/config.spec.js
- test/api/dht.spec.js
- test/api/diag.spec.js
- test/api/id.spec.js
- test/api/log.spec.js
- test/api/ls.spec.js
- test/api/name.spec.js
- test/api/object.spec.js
- test/api/pin.spec.js
- test/api/ping.spec.js
- test/api/refs.spec.js
- test/api/swarm.spec.js
- test/api/version.spec.js
All methods return a promise when not passed a callback
Closes #80
> feat: Add promise based api

- src/request-api.js
js-ipfs serves a content type including the charset
`application/json; charset=utf-8` so the previous check for
json failed, resulting in non parsed json.
Fixes https://github.com/ipfs/js-ipfs/pull/69/files#r53560321
> fix(request): Improve json content-type detection

- src/request-api.js
- test/request-api.spec.js
For example, when the response is a 200 OK without body
> Avoid crash for responses without 'content-type' header

- src/api/config.js
- test/api/config.spec.js
> Auto set json and bool flags on config.set

- src/api/swarm.js
- test/api/swarm.spec.js
- test/setup.js
> Implement all of the swarm API calls

- README.md
The name of the ipfs api global object has changed from `ipfsAPI` to `IpfsApi`. This PR will update the README to reflect the change.
> Fix browser instance instructions in README

- API.md
- CONTRIBUTING.md
- README.md
> Added Contribute, License, and Banner

- src/api/block.js
- test/api/block.spec.js
`block.put` now returns a rejected promise when no callback is provided and an error occurs; more tests.
> test: extend block coverage

- src/api/object.js
Ref https://github.com/ipfs/interface-ipfs-core/pull/7
> fix: add support for protobuf in object.put

- package.json
This pull request adds the newest [`bl`](https://www.npmjs.com/package/bl) to `dependencies`. It is intended to fix #275.
A (previuosly missing) linebreak is added to the file's ending because that's how the browser-based editor works on GitHub.
> require `bl` version `^1.1.2` in order to fix #275

- package.json
- src/api/add-stream.js
- src/get-files-stream.js
- src/load-commands.js
- src/request-api.js
> feature - createAddStream

- src/api/bootstrap.js
- src/index.js
- src/load-commands.js
- test/api/bootstrap.spec.js
Implement the bootstrap API in reference to issue #217 raised by @diasdavid
> Enhancement: Implement Bootstrap API

- package.json
- src/api/config.js
- src/get-files-stream.js
- src/request-api.js
- test/api/config.spec.js
> interface-ipfs-core config API spec compliant

- src/load-commands.js
Currently calling ```ipfs.add``` and ```ipfs.createAddStream``` will fail since the alias isn't picked up until after the ```ipfs.files``` command is called. 
Not sure if this is the best approach but this will allow people to use add with or without files until the namespace collision is solved.
This was referenced in issue #301 
@noffle could you check this and see if there could be any issues aliasing this way instead of how you had it.
> alias for add and createAddStream.

- package.json
- src/api/add.js
fixes https://github.com/ipfs/js-ipfs-api/issues/308#issuecomment-230104544
> fix files.add promises

- src/api/repo.js
- src/load-commands.js
- test/api/repo.spec.js
This adds support and test coverage for `repo.gc` and `repo.stat`, the two `repo` API methods supported by IPFS v0.4.1.
Support for other `repo` methods available in IPFS v0.4.2 depends on a pending update to the js-ipfsd-ctl dev dependency: https://github.com/ipfs/js-ipfsd-ctl/pull/80
> Adding repo API methods supported by ipfs 0.4.1

- src/get-dagnode.js
#This adds a check for the response from the go/js daemons to see if data is sending a stream or a buffer. This is needed for <a href="https://github.com/ipfs/js-ipfs/pull/323">PR</a>
@noffle for CR
> update get-dagNode for buffers

- .travis.yml
- package.json
- src/add-to-dagnode-transform.js
- test/interface-ipfs-core/files.spec.js
- test/interface-ipfs-core/get.spec.js
CI will be happy after https://github.com/ipfs/interface-ipfs-core/pull/56 is merged and released
> feat(files.add): conform with latest interface-ipfs-core spec

- src/add-to-dagnode-transform.js
- src/get-dagnode.js
ref: https://github.com/ipfs/js-ipfs/issues/214
> use modular async

- examples/browser-add-file/README.md
- examples/browser-add-file/index.html
- examples/browser-add-file/index.js
- examples/browser-add-file/package.json
Example showing broken file add in browser. See https://github.com/ipfs/js-ipfs-api/issues/344#issuecomment-243900156 and https://github.com/ipfs/js-ipfs-api/pull/335 for context.
> browser-add-file

- src/api/log.js
This fixes the broken master-build. Something worrying is that this doesn't always fail (the test for log.tail) when running all tests with `npm test`, but when running only that test, it always fails.
This PR should pass all CI though.
> fix: Return req from tail

- test/interface-ipfs-core/ls.spec.js
- test/interface-ipfs-core/refs.spec.js
> test: remove dependency on init doc hashes

- README.md
The site https://npmcdn.com/ has moved to https://unpkg.com/ (to refrain from using npm's name because of its [trademark policy](https://www.npmjs.com/policies/trademark), I presume).
Their name's change should be reflected in README.
> npmcdn.com → unpkg.com

- package.json
- src/api/object.js
Quick add of an lru-cache to js-ipfs-api for orbit. To make this effort complete we need:
> feat(object): add lru cache to object get/put

- package.json
- src/tar-stream-to-objects.js
Ref https://github.com/ipfs/js-ipfs/issues/498
Needs https://github.com/ipfs/interface-ipfs-core/pull/88
> fix(get): properly handled nested content

- README.md
This addition to README provides yet another example of CDN usage that ensures maximum security (but references a specific version of IPFS API).
The following minor changes are also introduced:
- “the Browser” → “a web browser”
- “through `<script>` tag” → “from CDN” (a necessary clarification because browserified versions, mentioned above it, are also likely to be used through `<script>`)
- the CORS-related problem (below) is specifically mentioned as affecting CDN-based IPFS API as well as browserified
> some security measures (for people not ready to trust their CDNs)

- package.json
- test/interface-ipfs-core/dht.spec.js
Needs https://github.com/ipfs/interface-ipfs-core/pull/36
> Move dht tests from js-ipfs-api to interface-ipfs-core

- package.json
- src/api/swarm.js
so obviously i don't javascript, but these tests failing my CI is getting old so i've made an effort.
Can someone who knows what they are doing help out here?
cc @diasdavid @dignifiedquire @VictorBjelkholm
> attempt to handle changes to ipfs swarm peers api

- package.json
- src/api/add.js
- src/api/block.js
- src/api/dht.js
- src/api/get.js
- src/api/log.js
- src/api/object.js
- src/api/ping.js
- src/api/refs.js
- src/api/util/fs-add.js
- src/api/util/url-add.js
- src/dagnode-stream.js
- src/get-dagnode.js
- src/request-api.js
- src/stream-to-json-value.js
- src/stream-to-value.js
- src/stringlist-to-array.js
- src/tar-stream-to-objects.js
- test/interface-ipfs-core/ping.spec.js
- test/interface-ipfs-core/refs.spec.js
- test/ipfs-api/util.spec.js
- test/setup/spawn-daemons.js
This PR will:
- Refactor the response stream handling.
- Add dagnode-stream to transform file results to DAGNode objects.
- Add stream-to-value to convert a response stream to a single value.
- Refactor request-api so that chunked JSON objects are not buffered anymore. This touches a bunch of the files pushing the transform function down to the individual commands.
The general idea in this PR is to  cleanup the architecture and implementation regards to how the http responses are handled. Previously some of it was done in request-api.js and some in the individual commands making request-api coupled with the commands' response type. I've moved the response transform logic down to the individual commands so that request-api is agnostic to what is returned to the consumer of the commands. …
> refactor(streams): Refactor response stream handling.

- src/clean-multihash.js
In the command-line tool you can have a hash followed by a path:
``` sh
ipfs cat QmXJ8KkgKyjRxTrEDvmZWZMNGq1dk3t97AVhF1Xeov3kB4/meta.json
```
Using ipfs-api before this patch I would get these errors when I try to do the same thing:
```
not valid multihash
```
With this patch, I get the expected output, the same as the command-line tool.
> fix so that multihashes may be followed by sub-path strings

- .gitignore
- README.md
- src/get-files-stream.js
- test/ipfs-api/util.spec.js
Also fixed [#408](https://github.com/ipfs/js-ipfs-api/issues/408) whilst in the area - `util.addFromFs` goes up almost to the root directory for files. It looks like for directories it was fixed in 42ccb0040b211ad302ab6e05e250e3b2024e626d, but it is now fixed for files too.
It looks like when the tests for this were written, someone expected addFromFs to go all the way up to the root dir in '.fsAdd a file' test/ipfs-api/util.spec.js- this seems like bizzare behaviour to expect, so I changed it.
> Adding ignore globs to fsadd.

- src/api/create-add-stream.js
Now that the importer stream constructor supports options, support it.
> support options in create-add-stream

- README.md
- src/get-files-stream.js
- test/fixtures/test-folder/.hiddenTest.txt
- test/ipfs-api/util.spec.js
Just passes through the option as specified in the [glob npm module](https://www.npmjs.com/package/glob)
https://www.npmjs.com/package/glob#dots
> Adding option for dotfiles in addFromFs

- package.json
Seems to have been missing since https://github.com/ipfs/js-ipfs-api/commit/43148150ec65d143481f6fab6e78bae461b8d745
> Add multihashes to package.json

- src/api/object.js
If one passes a plain object (like something returned from `toJSON`), `Links` are not copied over.
> Links have been ignored

- README.md
for https://github.com/ipfs/docs/issues/23
> docs: list out all the api calls

- README.md
- package.json
- src/api/pubsub.js
- src/load-commands.js
- src/pubsub-message-stream.js
- src/pubsub-message-utils.js
- test/interface/pubsub.spec.js
- test/ipfs-factory/daemon-spawner.js
- test/pubsub-in-browser.spec.js
Rebased onto master and squashed #471
> feat(pubsub): Add pubsub api

- src/api/refs.js
Currently a call to this API point will return an empty array.
> Fix incorrect API path for refs.local

- README.md
- src/api/key.js
- src/load-commands.js
- test/key.spec.js
Hi,
I needed that for my project so maybe it's useful for you as well :)
> Add key api from go-ipfs

- src/api/cat.js
- src/api/get.js
- src/clean-cid.js
go-ipfs supports CIDv1 for cat/get commands, so I guess it should also be supported here.
https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#cat should be updated if this gets merged.
> Use CID for api.get/api.cat

- README.md
even when linking to a 404 octocat, still better than the current empty links resolving to https://github.com/ipfs/js-ipfs-api/blob/master
> readme: added missing API links

- src/request-api.js
I will be making a PR against interface-ipfs-core to add a test for the scenario that failed without this
> fix: don't let qs mangle binary buffers (#569)

- src/object/addLink.js
This allows to send a multi-hash as a string as well.
> object patch add-link: don't force to have a Buffer for 'ref'

- src/util/url-add.js
- test/util.spec.js
fix #513 
That's the shortest path I found to solve this issue, but different solutions could be considered:
* delegating redirection handling to [`request.js`](https://github.com/ipfs/js-ipfs-api/blob/0295a5a1ad9754f83224d5a236fed94f5c7b202d/src/request.js)
* reintegrating a HTTP request library that handles it, but I guess you had your reasons to remove `wreck`
> Make url-add follow HTTP redirections

- src/utils/get-files-stream.js
- test/get.spec.js
Addresses #587 Preserve "+" in file paths.
> Support "+" character in file paths

- src/files/add.js
- src/files/create-add-stream.js
- src/utils/get-dagnode.js
- test/files.spec.js
Simply passes options to add command into the query string.
I've had to change `getDagNode` to be able to deal with a CID **or** a multihash as it's hash argument. This is because when specifying `--cid-version=1` we get back a CID in the response from `files/add`, and then the API uses `object/get` and `object/data` to fetch the content that was just added.
> Allow --cid-version option to be passed to ipfs files add

- src/api/add.js
- test/files.spec.js
Hey folks,
Great project! Thought I would update `ipfs.add` and `ipfs.files.add` to accept options, following the [function signature in your docs](https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#javascript---ipfsfilesadddata-options-callback):
`ipfs.files.add(data, [options], [callback])`
and the cli:
```sh
ipfs add [--recursive | -r] [--quiet | -q] [--quieter | -Q] [--silent] [--progress | -p] [--trickle | -t] [--only-hash | -n] [--wrap-with-directory | -w] [--hidden | -H] [--chunker=<chunker> | -s] [--pin=false] [--raw-leaves] [--nocopy] [--fscache] [--cid-version=<cid-version>] [--] <path>...
```
> Allow options with ipfs.add

- src/files/add.js
- src/object/data.js
- src/object/get.js
- src/utils/get-dagnode.js
- test/files.spec.js
This allows the optional param `hash` or `hashAlg` to be passed to `files.add` in order to specify the hash algorithm that should be used when generating the multihash(es) for the added content.
This PR also is more strict about what query string options `js-ipfs-api` supports by pulling out the supported params into a new query string object.
It also allows camel case aliases for params that are dash separated. This is because the HTTP API uses dash separated param names, but it is far easier to use camel case param names for internal APIs.
The other reason for allowing these aliases is because this code may be called when talking to a remote IPFS instance via the CLI where the qs params will have already been converted into camelCase.
This is necessary because `get-dagnode.js` uses …
> Support specify hash algorithm in files.add

- src/utils/request-api.js
While calling `request(config.protocol)` sets the right http protocol api to use it does not correctly pass the protocol information to node_modules/stream-http.
If the page is loaded over https and the daemon is located on http it fails to send the api request to the deamon.
This is because the code believes the daemon is located at https://127.0.0.1:5001/<insert api string here> when it is actually located at http://127.0.0.1:5001/<insert api string here>. 
Without this change the code throws an unrecoverable error and doesnt provide the user with information to fix the issue, with the change it still throws an error but it also lets the user resolve the issue by clicking the mixed content shield ![shield image](https://i.imgur.com/2kfXXGK.png) and allowing insecure content.
> pass the config protocol to http requests

- src/pin/add.js
- src/pin/ls.js
- src/pin/rm.js
As per discussion [here](https://github.com/ipfs/js-ipfs/pull/107#issuecomment-329704097), the pin methods should return results consistent with the [interface-ipfs-core API](https://github.com/ipfs/interface-ipfs-core/tree/master/API/pin).
> Make pin interface respect interface-ipfs-core API

- appveyor.yml
- src/utils/get-files-stream.js
- src/utils/request-api.js
- test/diag.spec.js
- test/ipfs-factory/client.js
- test/ipfs-factory/server-routes.js
- test/request-api.spec.js
See the discussion at https://github.com/ipfs/js-ipfs-api/issues/623
> Windows interop

- src/pubsub.js
- src/utils/pubsub-message-utils.js
See also https://github.com/ipfs/js-ipfs/pull/1081
> fix: allow topicCIDs from older peers

- src/pubsub.js
- src/utils/pubsub-message-stream.js
- src/utils/pubsub-message-utils.js
> Pubsub do not eat error messages

- src/config/replace.js
- src/utils/send-one-file.js
- test/request-api.spec.js
, which should now use the new streaming API.
(This wasn't caught on tests because `config.replace` tests are disabled <= this needs fixing)
Should fix #633.
> Fixed config.replace

- appveyor.yml
- src/utils/send-files-stream.js
- src/utils/send-request.js
fixes - https://github.com/ipfs/js-ipfs-api/issues/607
needs tests
> [WIP] fix: propagate trailer errors correctly

- README.md
- src/files/flush.js
- src/files/index.js
- test/files.spec.js
> feat: add files/flush

- package.json
- src/utils/prepare-file.js
`glob` is interpreting the '[' in `weird [v0]` as a special magic character.  According to its documentation, a caller should be able to escape it with `\`; but it does not work. See the [glob issue](https://github.com/isaacs/node-glob/issues/277).
Should fix [a directory with an odd name](https://github.com/ipfs/js-ipfs-api/pull/644).
> fix(files.add): handle weird directory names

- test/refs.spec.js
Symlinks in a repo don't always clone well, especially on Windows. So if the 'hello-link' is not a symlink, then make it one.
Should fix #645 and help with #644
> test(refs): fix symlinks from git

- test/request-api.spec.js
First reported in https://github.com/ipfs/js-ipfs-api/pull/648
```
4) 'deal with HTTP weirdness' tests does not crash if no content-type header is provided:
Uncaught AssertionError: expected [Error: read ECONNRESET] to not exist 
at ipfsAPI.config.replace (test\request-api.spec.js:28:28)
```
This is just a work around and does not fix the underlying problem.  I've changed the test to use `id` instead of `config.replace` and the test passes.
@diasdavid I'm think the `ECONNRESET` could be coming from push stream not being read by the server.  But perhaps it something else.  More eyeballs might help.  I think it's more of a timing/race issue than a specific windows issue
> test: HTTP weirdness

- src/utils/prepare-file.js
- test/files.spec.js
Prior to this PR, `ipfs.files.add([{ path: '', content: Buffer.from('TEST') }])` made error:
```
TypeError: content.once is not a function
at Multipart._pushFile (/Users/alan/Code/protocol-labs/js-ipfs-api/src/utils/multipart.js:80:13)
at Multipart._maybeDrain (/Users/alan/Code/protocol-labs/js-ipfs-api/src/utils/multipart.js:48:14)
at Multipart._transform (/Users/alan/Code/protocol-labs/js-ipfs-api/src/utils/multipart.js:40:10)
at Multipart.Transform._read (_stream_transform.js:185:10)
at Multipart.Transform._write (_stream_transform.js:173:12)
at doWrite (_stream_writable.js:399:12)
at writeOrBuffer (_stream_writable.js:385:5)
at Multipart.Writable.write (_stream_writable.js:292:11)
at eachSeries (/Users/alan/Code/protocol-labs/js-ipfs-api/src/utils/send-files-stream.js:52:35)
at …
```
> Fix empty path error

- package.json
- src/log/tail.js
- src/utils/converter.js
- src/utils/send-request.js
Bumps pump to version 2.0.
One nasty surprise:
Version 2.0 of pump does not return the last stream, which means that stuff like:
```
return pump(s1, s2)
```
does not work any more.
Track issue / feature request here: https://github.com/mafintosh/pump/issues/27
> chore: update dependency: pump version 2.0

- src/files/ls.js
- src/files/stat.js
- test/files.spec.js
This normalizes the object fields names by lower casing them. It also flattens the output of `files.ls`.
`files.ls` now returns an array of objects like:
```
{
name: 'something',
type: 0,
size: 0,
hash: 'something'
}
```
`files.stat` now returns an object like:
```
{
type: 'file',
size: 0,
hash: 'something',
blocks: 152,
cumulativeSize: 0
}
```
> breaking change: normalize fields and flatten output

- src/repo/index.js
- src/repo/version.js
- test/repo.spec.js
Add support for `api/v0/repo/version` calls.
related js-ipfs PR: [#1181](https://github.com/ipfs/js-ipfs/pull/1181)
> feat: /api/v0/repo/version

- README.md
- src/repo/stat.js
- src/repo/version.js
- src/stats/repo.js
- test/interface/repo.spec.js
- test/repo.spec.js
> fix(breaking change): spec repo

- README.md
- src/files/flush.js
- src/files/read.js
- test/files.spec.js
Use `streamToValue` on `files.read` to return a beautiful Buffer instead of a stream.
> feat(breaking change): stream to value on files read

- src/bitswap/stat.js
- test/bitswap.spec.js
This is also a breaking change.
> Some fixes regarding the Stats API

- package.json
- src/bitswap/stat.js
- src/repo/stat.js
- src/stats/bitswap.js
- src/stats/bw-pull-stream.js
- src/stats/bw-readable-stream.js
- src/stats/bw-util.js
- src/stats/bw.js
- src/stats/index.js
- src/stats/repo.js
`stats.bw` has an option called `poll` which allows the user to "tell" IPFS to send bandwidth stats each interval of time. We were collecting the response before calling the callback so that option would be useless. 
This way it sends a stream to the callback so the user can listen to `data` event which contains the Object.
Interface IPFS core update: https://github.com/ipfs/interface-ipfs-core/pull/211
> feat(breaking change): use stream on stats.bw

- src/ls.js
To be able to prettily print `ipfs ls -r`, we need to know the depth of each file from the `ls` command.
It was previously hardcoded a 1, though I don't know why. I'm passing the depth along from a change I made in js-ipfs [here](https://github.com/ipfs/js-ipfs/pull/1222/files#diff-dcaf16a1df33e0e8f40195e527b9294dR293).
The b58 hash test for `ls` should fail in CI because the above change to js-ipfs is required to receive the links' depth. Unfortunately this is a cyclical dependency. I can fix it by breaking out the change to js-ipfs or we can merge and fix if something comes up. lemme know
ref: https://github.com/ipfs/js-ipfs/pull/1222
> Make `ls` links' depth dynamic.

- src/stats/bw-pull-stream.js
- src/stats/bw-readable-stream.js
Removing an argument that wasn't supposed to exist.
> fix: remove argument from .stats.bw*

- package.json
- test/diag.spec.js
`process.platform` is only available in Node.js and not in the Browsers.
Hence the `diag.spec.js` tests weren't correctly skipped on Windows.
> fix: disable Browser test on Windows

- test/util.spec.js
The previous server had issues, so the test timed out. Hopefully
this on is more stable.
> Use a different remote server for test

- package.json
This commit introduces a new experimental branch of AEgir which
should fix the issue with taking to much memory when running the
Browser based tests. If it turns out to be successful, there
will be a new AEgir release containing that fix.
> fix: don't create one webpack bundle for every test file

- src/files/add-pull-stream.js
- src/files/add-readable-stream.js
- src/files/add.js
- src/files/write.js
- src/util/fs-add.js
- src/util/url-add.js
- src/utils/converter.js
- src/utils/file-result-stream-converter.js
- src/utils/send-files-stream.js
The `SendFilesStream` used to run the `FileStreamConverter` automatically.
With making it an option to use a converter, `SendFilesStream` can be
used outside of the Files API, e.g. for the DAG API.
> Set the FileStreamConverter explicitly 

- src/dht/provide.js
This PR validates that the `cid` argument passed to provide is a CID and also serializes it to a base58 encoded string as the serialization job done by `qs` appears to be ignored by go-ipfs.
Please see [this discussion](https://github.com/ipfs/interface-ipfs-core/pull/221#issuecomment-370938018) for the context.
> fix: validates and serializes cid argument to dht.provide

- src/files/stat.js
- test/files.spec.js
So, I upgraded my js-ipfs-api and found out that the support for `ipfs files stat --with-local` was broken after 98000af3fe9c15aa7f6a594f760bff2f3d373095 (the response object is not relayed entirely anymore, so the new values get dropped).
Another problem I had and that is not solved yet by this PR is that due to the migration in go-ipfs to the new `go-ipfs-cmds` framework (https://github.com/ipfs/go-ipfs/pull/4638), the command `ipfs files stat` now reply with a stream which is not converted properly in values by js-ipfs-api. There is two way to solve that problem:
- convert the stream in a single value in js-ipfs-api
- use `cmds.EmitOnce` in go-ipfs to hint the ReponseEmitter and reply without streaming
Do you have a preference ?
CC @whyrusleeping, @Stebalien
> add support for ipfs files stat --with-local

- .aegir.js
Sometimes on the CI Browser tests were timing out, hence increase it.
> test: increase Karma timeout

- examples/upload-file-via-browser/src/App.js
While trying to look at the upload-via-browser example, I spent some time trying to figure out what arrayBufferToString was supposed to do and it looks like it's some leftover from a previous version of the example and it's currently not being used.
It would be great to have this removed in order to avoid confusion.
> Cleanup upload-via-browser example

- README.md
- package.json
- src/ping-pull-stream.js
- src/ping-readable-stream.js
- src/ping.js
- src/utils/load-commands.js
- src/utils/send-request.js
- test/ping.spec.js
- test/sub-modules.spec.js
This should close #556 and add two additional methods to stream the ping results.
> feat: streamable ping and optional packet number

- src/utils/send-files-stream.js
For https://github.com/ipfs/js-ipfs/issues/1178
Adds awareness of new wrapWithDirectory parameter which will be passed along to the api via querystring.
> feat: add awareness of wrapWithDirectory option to utils/send-files-stream

- README.md
- src/index.js
- src/util/get-endpoint-config.js
- src/utils/load-commands.js
- test/util.spec.js
Added a util getter for obtaining the host and port.
Closes #580
> feat: public readonly method for getting host and port

- README.md
Updates link in readme
- ~~https://github.com/ipfs/interface-ipfs-core/tree/master/src~~
- https://github.com/ipfs/interface-ipfs-core/tree/master/js/src
> Fix link to interface tests in README

- src/util/url-add.js
- test/util.spec.js
`ipfs.util.addFromURL` now works well with the `wrapWithDirectory` option.
> Fix #140: ipfs add url wrap doesn't work

- test/name.spec.js
`name.publish` takes forever! I've increased the timeout to 5 minutes to accommodate.
I also moved the test (which adds a file for future tests) into the `before` block, I've removed the assertions that this test was making (there should be adequate tests for adding files elsewhere) and instead of hard coding the CID I've extracted it from the return value of the `files.add` call.
> fix: increase timeout for name.publish and fix setup code

- src/files/get.js
- test/commands.spec.js
- test/constructor.spec.js
- test/get.spec.js
- test/ping.spec.js
- test/util.spec.js
Blocked on:
- https://github.com/jbenet/node-subcomandante/issues/8 to get Circle Green
> get it ready for release

- test/bitswap.spec.js
- test/commands.spec.js
- test/constructor.spec.js
- test/diag.spec.js
- test/files.spec.js
- test/get.spec.js
- test/key.spec.js
- test/log.spec.js
- test/name.spec.js
- test/ping.spec.js
- test/pubsub-in-browser.spec.js
- test/refs.spec.js
- test/repo.spec.js
- test/stats.spec.js
- test/types.spec.js
- test/util.spec.js
If failed start node in `before`, do not fail stop node in `after`.
It reduces the noise from IPFS node start failures by fixing the after hook so it doesn't also error when trying to stop a node that didn't start.
e.g.
```
4) .refs "before all" hook:
Uncaught AssertionError: expected [Error: connect ECONNREFUSED 127.0.0.1:53477] to not exist
at ipfsd.api.id (test\ping.spec.js:47:30)
at send (node_modules\ipfsd-ctl\node_modules\ipfs-api\src\id.js:19:16)
at f (node_modules\once\once.js:25:25)
at ClientRequest.req.on (node_modules\ipfsd-ctl\node_modules\ipfs-api\src\utils\send-request.js:168:5)
at Socket.socketErrorListener (_http_client.js:387:9)
at emitErrorNT (internal/streams/destroy.js:64:8)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback …
```
> fix: do not fail stop node if failed start node

- src/swarm/peers.js
A call to `swarm.peers` can give back a result object that looks like `{ Peers: null }`. This meant the callback was never called due to a `else if (result.Peers)` that doesn't take into account a `null` `Peers`, and no else block.
I believe this is the source of much of the "flakeyness" in the tests.
> fix(swarm): result.Peers can be null, ensure callback is called

- src/pubsub.js
This PR changes the `unsubscribe` logic to only callback on the last event we can listen for on a dropped connection.
This **still** does not guarantee that your topic won't appear when calling `pubsub.ls` in the callback to `pubsub.unsubscribe` - **but only when talking to go-ipfs**.
Adding an artificial timeout using `setTimeout` _seems_ to provide enough time for go-ipfs to actually do the unsubscribe.
> fix(pubsub): callback from unsubscribe after stream ends

- README.md
- test/constructor.spec.js
After @alanshaw [suggestion](https://github.com/ipfs/js-ipfs-api/pull/744), I added docs and a test for the `api-path` usage in the API constructor.
Closes #581
> chore: Add api path docs and test

- src/util/url-add.js
- test/util.spec.js
This PR solves double-URL-escaping problem happening when already escaped  filename is added to IPFS via `ipfs.util.addFromURL` with `wrap-with-directory=true`.
(Originally issue found while working on https://github.com/ipfs-shipyard/ipfs-companion/issues/349)
```js
ipfs.util.addFromURL('https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Doma%C5%BElice%2C_Jir%C3%A1skova_43_%289102%29.jpg/320px-Doma%C5%BElice%2C_Jir%C3%A1skova_43_%289102%29.jpg?foo=bar#buzz', {wrapWithDirectory: true}, (err, result) => {
if (err) {
throw err
}
console.log(result)
})
```
Wrapping directory contains URL-escaped file name:
320px-Doma%C5%BElice%2C_Jir%C3%A1skova_43_%289102%29.jpg
Wrapping directory should list file under original name:
320px-Domažlice,_Jiráskova_43_(9102).jpg
> fix(util): addFromURL with URL-escaped file names

- examples/bundle-browserify/package.json
- examples/bundle-webpack/package.json
- examples/name-api/package.json
- examples/sub-module/package.json
- examples/upload-file-via-browser/package.json
- package.json
> Our rule is: Use ~ for everything below 1.0.0 and ^ for everything above 1.0.0. If you find a package.json that is not following this rule, please submit a PR.
https://github.com/ipfs/community/blob/master/js-code-guidelines.md#dependency-versions
> chore: use tildes for pre-v1 deps

- .aegir.js
Big.js just released an update that added esmodule support by adding a "module" field to their package.json. By default, webpack will use this field when requiring a module. Since esmodules aren't fully supported in the browser and we don't do any transpiling this PR configures webpack to not consider the esmodule field.
[Webpack `mainFields` docs](https://webpack.js.org/configuration/resolve/#resolve-mainfields)
[Why `require('big.js')` is broken for us](https://github.com/webpack/webpack/issues/4742)
Refs https://github.com/ipfs/js-ipfs/issues/1363
Note that this solves the issue for `big.js`, but also for any other modules in the future that decide to define a `module` field in their `package.json` or any that already do and we just haven't realised it yet!
> fix: configure webpack to not use esmodules in dependencies

- test/ping.spec.js
These have been observed to take a little over the default 2s in web browsers/workers so are intermittently failing on CI and locally.
> fix: increase timeout for ping tests

- package.json
- src/utils/stream-to-json-value.js
The dht.findprovs endpoint is inconsistent with the other endpoints when reporting errors. It sends a message like:
```
argument "key" is required
```
While others wrap it in a JSON object with more info:
```
{"Message":"Invalid base58 digit ('-')","Code":0,"Type":"error"}
```
This breaks our parser because it is expecting that the messages are standardized.
I'm testing these with the https://github.com/ipfs/interface-ipfs-core/pull/288
> test: dht testing

- package.json
- src/files/cp.js
- src/files/ls.js
- src/files/mv.js
- src/utils/find-sources.js
- test/files.spec.js
See ipfs/interface-ipfs-core#277 for more information
> chore: update method signatures in line with ipfs/interface-ipfs-core#277

- package.json
- src/block/get.js
Found this very strange bug when creating DAGNode's with empty buffers for data.
streamToValue returns an empty array when the data is empty, which down the line triggers an exception in ipfs-block because this sends an empty array instead of a buffer.
> Fix for empty data in block.

- package.json
- test/name.spec.js
- test/ping.spec.js
Make the tests pass again finally
depends on https://github.com/ipfs/interface-ipfs-core/pull/311
> chore: increase ping and name test timeouts

- src/utils/send-request.js
- test/files.spec.js
Also maps 'Type' property from error responses
> chore: logs path & querystring for requests

- package.json
- src/dag/put.js
- test/util.spec.js
**Note: Only review last commit as it's rebased on top of #785 to make test runner work**
This is to align with API changes in 
https://github.com/ipfs/interface-ipfs-core/commit/011c417b97e58aceafaa4e98fce8f32217bc5cf7
and
https://github.com/ipfs/js-ipfs/pull/1415
**Temporarily rebased on top of #785**
Note: this is a WIP as I have to run now :D will make tests green once I'm back
> fix(dag): ensure `dag.put()` allows for optional options

- src/files/cp.js
- src/files/flush.js
- src/files/mkdir.js
- src/files/mv.js
- src/files/rm.js
Most of the mfs commands have no response body but our client returns the response object that then has a stream which resolves to an empty string.  This causes problems with the interop tests as you can't easily compare the two response objects so we should probably just ignore the response of any method we know will either return an error or nothing at all.
Also makes invocations over http consistent with invoking core directly.
> chore: ignore response body for some mfs commands

- src/utils/send-request.js
When ipfs-api runs inside Electron, isNode is true, but res.req is undefined. And the request logging is breaks the lib.
It will be better to check whether res.req is set instead of relying on detect-node.
fixes #807
> Fix Request logging broken in Electron

- .aegir.js
- package.json
- test/name.spec.js
Seeing this timeout on multiple environments and Node.js versions so have given it an extra 5s.
Also increases the `browserNoActivityTimeout` to give the `dht.query` test time to [fail but pass anyway](https://github.com/ipfs/interface-ipfs-core/blob/87a8f96b74987ab6d477dc73a91d9f32ff066267/js/src/dht/query.js#L46-L52) - previously the `browserNoActivityTimeout` wasn't taking into account the extra 60s allocated to the before hook, so I just added it here.
> fix: increase name after timeout

- src/config/set.js
`config.set` should be rejecting buffer values[0]. Currently it accepts them because a buffer returns `typeof` of `object`, and is serialized into an object `{type: 'buffer', data: [...]}`.
This change brings the type checking of the `value` field inline with the `js-ipfs-repo`[1].
More info: https://github.com/ipfs/interface-ipfs-core/issues/320
[0] https://github.com/ipfs/interface-ipfs-core/blob/ef910266b36c89fe21f9821f86bdb9955d60b468/js/src/config/set.js#L82-L87
[1] https://github.com/ipfs/js-ipfs-repo/blob/a7ea45bac6f1c264f86e79357f702314758a48f1/src/config.js#L65-L67
> fix: config.set should reject buffer values

- src/dag/get.js
- test/dag.spec.js
Right now `ipfs.dag.get` fails silently for CIDs with codecs different than `dag-cbor` or `dag-pb`.
To reproduce, try `dag.get` for  `raw` one at  `bafkreigh2akiscaildcqabsyg3dfr6chu3fgpregiymsck7e7aqa4s52zy`.
This PR fixes the bug by returning error when codec resolver is missing. 
Notes:
- Problem occurs only in js-ipfs-api, js-ipfs already delegates resolvers to ipld which has proper error handling  [here](https://github.com/ipld/js-ipld/blob/19498948477af8e33018b7472e76f02d4df926f6/src/index.js#L163).
- Added regression tests for `dag.put+get`, not sure if it is the right place tho. Any feedback would be appreciated.
- Not sure what is the long term plan for resolvers,  I assume endgame will be https://github.com/ipfs/js-ipfs-api/pull/755 ?
> Fix for dag.get failing silently on missing multicodec

- test/dag.spec.js
See https://github.com/ipfs/js-ipfs-api/pull/806#issuecomment-412838846 for context.
> fix: add test data to IPFS before fetching it

- src/object/get.js
Requires ipfs/js-ipfs#1420 to be merged in order to allow the test in ipfs/interface-ipfs-core#302 to pass.
> chore: use data-encoding arg to ensure data is not corrupted

- src/utils/request.js
The way `http.request` is currently being included makes it a huge pain to mock the api requests with something like `nock`, since the request function cannot be stubbed the way it's being included.
This PR changes the way .request is being included, to allow for easier mocking.
I am using this change locally with nock to test some upcoming module additions to libp2p.
> test: allow for easier mocking of requests

- README.md
> Update link to JS tests inside of interface-ipfs-core

- package.json
- src/block/put.js
- test/interface.spec.js
Alternative to #793 
Should fix this according to [the spec](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/BLOCK.md#blockput).
fixes #815 
closes #793
~~tested by https://github.com/ipfs/interface-ipfs-core/pull/370~~ (released)
> fix: block.put options

- examples/bundle-browserify/index.js
- examples/bundle-browserify/package.json
Change API name and ipfs-api version to make the example work with newer js-ipfs-api versions.
Because ipfs.files.cat expects `stream` for response in recent versions, `{buffer: true}` option cause a crash (stream.pipe not defined).
> small fix to bundle-browserify for recent js-ipfs-api

- package.json
Switching ASAP to the latest version of `stream-http` with the fix by @hugomrdias \o/
Context: https://github.com/jhiesey/stream-http/pull/93
Closes #654 cc https://github.com/ipfs/in-web-browsers/issues/115
> fix: >150mb bodies no longer crashing Chromium

- package.json
Add lodash as a dependency because it's required in 2 files.
This PR is related to [PR 871](https://github.com/ipfs/js-ipfs-api/pull/871).
@alanshaw this follows the requirements of the build tool. Sorry for that!
> fix: add lodash dependency

- src/types.js
- test/types.spec.js
Prior to this change the `ipld-dag-cbor` and `ipld-dag-pb` modules
are re-exported so that can be accessed within the Browser bundle.
Those modules normally don't need to be used directly, they are
kind of implementation details of IPLD. Hence remove them.
BREAKING CHANGE: remove `types.dagCBOR` and `dag.dagPB` from public API
> chore: remove ipld formats re-export

- src/pin/ls.js
`ipfs.pin.ls` may get really slow for mid-large repos, especially when called without executing with `opts = {type: recursive}`. 
Unfortunately passing `opts` does not work right now: it is set to null if `hash` is also present.
[`interface-ipfs-core`](https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/pin/ls.js) does not include proper tests for scenario when both `hash` and `opts` params are present, so it was not detected until I tried to use it in ipfs-companion (https://github.com/ipfs-shipyard/ipfs-companion/issues/360#issuecomment-427525801)
This PR fixes the bug by restoring passing of `opts`.
I add missing test cases to [`interface-ipfs-core/js/src/pin/ls.js`](https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/pin/ls.js) in …
> fix: pin.ls ignored opts when hash was present

- examples/upload-file-via-browser/package.json
- examples/upload-file-via-browser/src/App.js
Old example used deprecated practice of  pre-allocating a Buffer from the file handle.
While it worked fine for small files, with bigger ones introduced artificial limit of ~2GB and caused `RangeError: Attempt to allocate Buffer larger than maximum size: 0x7fffffff bytes` 
People look at  `examples/upload-file-via-browser` to learn "best practices", so I updated it to follow what we learned and do in ipfs-companion, ipfs-webui and ipfs-share-files.
**tl;dr**
- This change replaces Buffer with a pull stream, which enables example to work with big files 
(tested with 3.6GB video, took ~30seconds to add to local go-ipfs).
- While I was at it, I added a demo of a pattern for persisting filenames by wrapping them in unixfs directory (very popular question). 
- …
> feat: upload example works with big files

- src/block/put.js
Prevents error unrecognized format: 'dag-cbor'
> fix: also retry with misnamed format "dag-cbor" as "cbor"

- examples/bundle-browserify/package.json
- examples/bundle-webpack/package.json
- package.json
- src/object/addLink.js
- src/object/new.js
- src/object/put.js
- src/utils/clean-multihash.js
Follows on from https://github.com/ipld/js-ipld-dag-pb/pull/99 and updates this module to not rely on DAGNodes having knowledge of their CIDs.
> fix: updates ipld-dag-pb dep to version without .cid properties

- examples/upload-file-via-browser/package.json
- examples/upload-file-via-browser/src/App.js
- examples/upload-file-via-browser/webpack.config.js
Packages used in the `upload-file-via-browser` demo is too old.
The PR update all of them and fixed all the warnings.
> Update dependencies & config for `upload-file-via-browser` demo.

- test/log.spec.js
This got broken in go-ipfs 0.4.18, I have no idea why it worked before..
> Fix log.tail by calling add after listening for events

- .gitignore
- .npmignore
- package.json
- src/files-regular/add-from-url.js
- src/files-regular/add.js
- src/files-regular/get-readable-stream.js
- src/files-regular/ls-readable-stream.js
- src/utils/send-files-stream.js
- test/dag.spec.js
- test/interface.spec.js
requires https://github.com/ipfs/interface-ipfs-core/pull/376
> fix: better input validation for add

- CHANGELOG.md
Didn't make it into the autogenerated changelog as the commit message wasn't quite in the correct format (https://github.com/ipfs/js-ipfs-http-client/commit/6e6d7a2520b5bf89ba56d9bd0d5d8fcdc75c760b)
> fix: add docs for breaking change

- README.md
(afaik) HTTP API does not need this and we should not ask people to set it if they don't really need it.
See also:
- Potential problem with  `Access-Control-Allow-Credentials`: https://github.com/ipfs/go-ipfs/issues/5745
- HTTP Headers Cleanup: https://github.com/ipfs/in-web-browsers/issues/132
> docs(readme): remove CORS Credentials header

- package.json
- src/files-mfs/index.js
- src/files-mfs/ls-pull-stream.js
- src/files-mfs/ls-readable-stream.js
- test/interface.spec.js
N.b will not actually do any streaming until https://github.com/ipfs/go-ipfs/pull/5611 is released.
> feat: add files.ls streaming methods

- CHANGELOG.md
- README.md
- src/files-regular/index.js
- test/interface.spec.js
- test/sub-modules.spec.js
This was incorrectly `addFromUrl` in some places...
> fix: case for addFromURL

- package.json
- src/files-regular/ls-pull-stream.js
- src/files-regular/ls-readable-stream.js
- src/files-regular/ls.js
- src/utils/clean-cid.js
- test/interface.spec.js
The CID version agnostic tests https://github.com/ipfs/interface-ipfs-core/pull/413 identified some functions were not properly serializing CID instances. This PR adds `cleanCID` step to several functions and also updates the `cleanCID` function to not assume buffer CIDs are CIDv0 multihashes.
> fix: properly serialize CID instances

- src/files-mfs/ls-readable-stream.js
This way the requiring lib doesn't have to support the spread operator.
> chore: use Object.assign instead of spread operator

- package.json
- src/files-regular/ls-pull-stream.js
- src/files-regular/ls-readable-stream.js
- src/files-regular/ls.js
This was accidentally disabled and no tests existed to catch it.
> fix: re-allow passing path to ls

- package.json
Including `ipfs-http-client` in the `browser` field of package.json was causing Meteor to not include the bundle in it's browser build.
I have no idea why it is there! @daviddias do you remember why it was added?
fixes #924
> fix: bundle in meteor

- README.md
- src/util/get-endpoint-config.js
- test/util.spec.js
The protocol is used to construct the request, and it's useful to be able to check it has been set correctly. This PR adds it to the `util.getEndpointConfig()` return value.
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
> feat: return protocol from getEndpointConfig

- package.json
Readme says that minimum Node.js version is 10. This is true because of some dependencies which also require version 10. However, in `package.json` file, minimum version is 8. This is incorrect, so I'm fixing this now.
> Update required Node version

- package.json
- test/commands.spec.js
- test/constructor.spec.js
- test/custom-headers.spec.js
- test/dag.spec.js
- test/diag.spec.js
- test/files-mfs.spec.js
- test/get.spec.js
- test/key.spec.js
- test/log.spec.js
- test/name.spec.js
- test/ping.spec.js
- test/pubsub-in-browser.spec.js
- test/refs.spec.js
- test/repo.spec.js
- test/stats.spec.js
- test/util.spec.js
- test/utils/interface-common-factory.js
Urh, this is kind of amazing, it took the node.js test time down from 13m49.208s to 5m15.992s 😱 (for me locally)
For reference, this is what using the "test" profile does: https://github.com/ipfs/go-ipfs-config/blob/master/profile.go#L68-L85
resolves https://github.com/ipfs/js-ipfs-http-client/issues/593
Depends on:
> perf: use test profile

- src/dht/findprovs.js
> fix: dht.findProvs.js handle valid hash but no providers

- package.json
- src/index.js
- test/constructor.spec.js
Pointing Web UI at `/https` multiaddr did not work: it was not able to connect to API over HTTPS, always tried HTTP (https://github.com/ipfs-shipyard/ipfs-webui/issues/989):
> ![](https://user-images.githubusercontent.com/157609/55738075-aaa97480-5a26-11e9-945d-12a53b943326.png) 
I tracked the bug up to `ipfs-http-client` constructor: only `host` and `port` were read from multiaddr, `protocol` was ignored and unencrypted HTTP was used for all multiaddrs:
https://github.com/ipfs/js-ipfs-http-client/blob/21cdcc5100b32e3ac1e75ec70022b9b28b0aede1/src/index.js#L27-L28
This PR:
- improves parsing of multiaddr constructor parameter
- adds tests to ensure HTTPS is respected in all scenarios
- updates iso-stream-http to v0.1.2 which includes unrelated fix for "https does not exist" error
> Fix support for /https multiaddrs passed to constructor

- package.json
- src/index.js
Closes #964
We should backport this to js-ipfs.
Explicit require of buffer can actually be enforce by linter to avoid these and other issues with node/browser stuff.
> fix: fix missing buffer bundling with browserify

- package.json
This switches pull-to-stream to v0.1.1 which includes a fix `Uncaught Error: stream.push() after EOF` and truly closes #967 in all build pipelines (semver seems to be  not enough when yarn lockfile is used)
> fix: Uncaught Error when adding files bigger than 1MB

- .travis.yml
- package.json
Also adjust Travis CI config to perform builds and tests with node 8.
`npm install`, `npm run build`, and `npm run test` all succeeded locally with node version `8.3.0`.
The reason for version `8.3.0` instead of `8.0.0` is that `8.3.0` introduced support for object rest/spread, which is used by at least one of this package's devDependencies (`go-ipfs-dep`, in production install of that devDep). It may be the case that at runtime older versions of node would work correctly with the built package, but it seems simpler to settle on the minimum supported version being a version that can build, test, and use the package.
Closes #983.
> build: change min node version to 8.3.0

- package.json
- src/config/set.js
Anything that isn't a string needs to be passed with `--json`.
fixes #881
Depends on:
cc @0x6431346e @koalalorenzo
> fix: config set with number

- src/dht/findprovs.js
Correcting the array check to happen before the individual element checks. fixes https://github.com/ipfs/js-ipfs-http-client/issues/928
> Handle Empty Array return values for findProvs method

- src/utils/send-files-stream.js
Looks like this was missed off..
> fix: actually send the param to trigger the trickle dag builder

- src/utils/send-request.js
- src/utils/stream-to-json-value.js
- test/request-api.spec.js
Better error reporting by detecting `Content-Type` of the response and not attempting to parse JSON for non-`application/json` responses.
resolves #912
resolves #1000
closes #1001
> fix: error reporting for non-JSON responses

- .aegir.js
We added some functionality and made it a tiny bit bigger, sorry. This will hopefully come down again when we switch to async await and async iterators.
> chore: update min bundlesize

- src/dht/findprovs.js
I'm not sure why this is the case, but sometimes go returns no `.Addrs` property in the `dht.findProvs` response.
> fix: sometimes no Addrs element is present in the response

- package.json
- src/repo/gc.js
BREAKING CHANGE: repo.gc response objects have changed to `{ err, cid }`
Depends on:
> GC endpoint

- src/dht/findpeer.js
- src/dht/findprovs.js
- test/interface.spec.js
Pick out the correct item from the response, do not assume the first is the one we want.
Also calls `toString` on the CID/PeerID so that we can pass CID instances directly to these functions.
> fix: response for findpeer and findprovs

- examples/name-api/package-lock.json
- examples/name-api/package.json
Switch to using `extatic` (a maintained fork of `ecstatic`) instead of http-server (which uses `ecstatic`)
> docs: fix ecstatic security vulnerability in name-api example

- package.json
- src/dht/findprovs.js
- test/interface.spec.js
Find providers was not consistently returning all of the provider responses. This was causing flakey test failures for https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/9.
It will now properly return all response records for each result.
> fix: make findprovs return all responses

- package.json
- src/dag/get.js
- test/dag.spec.js
Also support for loading raw blocks.
> feat: add support for js-ipfs dag api and also some tests

- src/utils/send-files-stream.js
This PR is the counterpart of https://github.com/ipfs/go-ipfs-files/pull/8
According to https://tools.ietf.org/html/rfc7578#section-4.2, in a Content-Disposition header
of a part in a multipart/form-data body:
- the disposition must be of type `form-data`
- a `name` parameter (not explicitely specified by the RFC, but I suppose non-empty)
As this `name` parameter is unused by IPFS, this commit simply generate a placeholder with
a counter, to conform to the HTTP specification.
I couldn't test properly that this fix actually works properly, so please test thoroughly.
> fix multipart/form-data

- README.md
Link to relevant MFS and DAG API tutorials on ProtoSchool, as part of the Q3 IPFS Docs task force efforts. See issue https://github.com/ProtoSchool/protoschool.github.io/issues/260
> Link to ProtoSchool tutorials

- package.json
- src/object/stat.js
- test/interface.spec.js
The ipfs object stat command couldn't handle the {timeout: '1s'} option (or any other options). We're already checking for the opts parameter so it makes sense that we should be sending it as well. 
Things work as desired now with this one line addition.
Depends on:
> Added opts to object stat command

- greenkeeper.json
Too much greenkeeper noise and they are not critical to the project.
> chore: silence greenkeeper in examples

- src/files-regular/add-async-iterator.js
- src/files-regular/index.js
- src/utils/load-commands.js
Adds a method called `ipfs._addAsyncIterator`, prefixed with an underscore to mark it as sort of unofficial (though it's what `ipfs.add` will become once the async iterator migration is complete) and we don't want to implement symmetrical `ipfs.catAsyncIterator` etc methods, or at least not yet.
Also adds support for sending the `pin` and (non-standard, JS-specific) `preload` arguments via HTTP.
> feat: support adding files via async iterator

- .aegir.js
- .travis.yml
- package.json
- src/add/form-data.browser.js
- src/add/form-data.js
- src/dht/findpeer.js
- src/id.js
- test/get.spec.js
- test/interface.spec.js
- test/utils/interface-common-factory.js
- temp fix for electron renderer until ky-universal is fixed
- Blob can accept Buffer directly
- Buffer.buffer triggered a super weird bug in electron renderer
- enable a bunch of tests in the browser
- xvfb-run makes electron go crazy
- detect-node needs to be removed everywhere and ipfs-utils/src/env.js should be used
- If you mix promises and callbacks inside, call the callback with setImmediate
> fix: fix electron renderer tests and a couple more bugs

- package.json
- test/commands.spec.js
- test/constructor.spec.js
- test/custom-headers.spec.js
- test/dag.spec.js
- test/diag.spec.js
- test/endpoint-config.spec.js
- test/exports.spec.js
- test/files-mfs.spec.js
- test/get.spec.js
- test/key.spec.js
- test/lib.configure.spec.js
- test/lib.error-handler.spec.js
- test/lib.stream-to-iterable.spec.js
- test/log.spec.js
- test/node/swarm.js
- test/ping.spec.js
- test/repo.spec.js
- test/request-api.spec.js
- test/stats.spec.js
- test/sub-modules.spec.js
This is to work around https://github.com/chaijs/chai/issues/1298
Fundamentally we cannot pull in chai and add plugins to it without being careful of the order of those plugins as it's a singleton.
All we're really interested in is the `expect` function to just get the preconfigured one from the interface tests.
> fix: pull in preconfigured chai from interface tests

- src/add-from-fs/index.js
- src/add-from-url.js
- src/pubsub/subscribe.js
I noticed some calls would fail during tests when the daemon was listening on non-standard ports, this was because when commands `require` other commands that use `ky`, we are passing the `ky` instance in as the sole property of an object that usually contains the host and port number of the remote node's API server.
> fix: get correct remote node config

- .travis.yml
Disable building branches that aren't `master` or `release/*` - builds will happen for all PRs anyway, so this change means we don't get a branch build and a PR build on each PR.
The intention is to maintain `release/vN.x.x` branches similarly to `ipfs/js-ipfs` in case we need to backport fixes to older versions.
> chore: avoid double travis build for PRs

- src/add/index.js
Only came up when testing `js-ipfs`, I think because preloading is not a thing in `go-ipfs` so we don't have much (any?) of it in the interface tests, and at any rate the interface tests of `js-ipfs-http-client` are run against `go-ipfs`.
Fixes broken build of https://github.com/ipfs/js-ipfs/pull/2555 and others.
> fix: use non-strict equivalence for options.preload

- CHANGELOG.md
> docs: add kebab case breaking change

- package.json
- src/name/resolve.js
- test/interface.spec.js
This PR updates to `interface-ipfs-core": "^0.118.0` which includes test for resolving paths with libp2p-key represented as CIDv1 Base32.
The problem is that go-ipfs 0.4.22 does not support PeerID as CID, so test added in https://github.com/ipfs/interface-js-ipfs-core/pull/553 fails:
```
1) interface-ipfs-core tests
.name.resolve offline
should resolve a record from peerid as cidv1 in base32:
Error: not a valid proquint string
```
<del>@alanshaw  not sure how to handle this. Wait for go-ipfs v0.5.0? Fixup on the fly in the meantime?</del>
<del>A hacky way to support CIDs when API is go-ipfs 0.4.22 or older is to convert toBase58btc before sending. See below.</del>
For now we skip cidv1b32 test, added todo to unskip when go-ipfs ships with native support.
closes …
> feat: support name.resolve of peerid as cid

- package.json
- src/block/get.js
- src/block/index.js
- src/block/put.js
- src/block/stat.js
- src/dag/get.js
- src/dag/index.js
- src/dag/put.js
- src/dag/resolve.js
- src/lib/buffer-to-form-data.browser.js
- src/lib/buffer-to-form-data.js
- src/utils/load-commands.js
> refactor: convert block API to async await

- src/config/get.js
- src/config/index.js
- src/config/profiles/apply.js
- src/config/profiles/index.js
- src/config/profiles/list.js
- src/config/replace.js
- src/config/set.js
- src/lib/error-handler.js
- src/utils/load-commands.js
- test/lib.error-handler.spec.js
- test/request-api.spec.js
BREAKING CHANGE: Errors returned from request failures are now all [`HTTPError`](https://github.com/sindresorhus/ky/blob/c0d9d2bb07e4c122a08f019b39e9c55a4c9324f3/index.js#L117-L123)s which carry a `response` property. This is a [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) that can be used to inspect _all_ information relating to the HTTP response. This means that the `err.status` or `err.statusCode` property should now be accessed via `err.response.status`.
> refactor: convert config API to async await

- package.json
- test/interface.spec.js
- test/utils/interface-common-factory.js
This PR allows interface-core tests to create and spawn nodes asynchronously.
Related to:
https://github.com/ipfs/interface-js-ipfs-core/pull/562
> chore: change interface tests to async node creation

- package.json
- src/pin/ls.js
Fixes `pin.ls` with multiple CIDs, which was inadvertently unsupported since it wasn't documented but was being tested for in js-ipfs CLI tests.
https://github.com/ipfs/interface-js-ipfs-core/pull/563 adds a test and documents the feature.
> fix: pin ls with multiple CIDs

- .aegir.js
- package.json
This PR refactors `.aegir.js` `pre` and `post` hooks. With https://github.com/ipfs/interface-js-ipfs-core/pull/565 refactor, there is no need to promisify both echo-server `start()` and `stop()`.
It also removes [`promisify-es6`](https://github.com/manuel-di-iorio/promisify-es6) dependency because it is not needed anymore. 
Depends on:
- https://github.com/ipfs/interface-js-ipfs-core/pull/565
> refactor: use echo-server start and stop functions as promises

- package.json
- src/files/flush.js
> fix: return CIDs from files.flush

- src/files/chmod.js
- src/files/cp.js
- src/files/mkdir.js
- src/files/mv.js
- src/files/touch.js
BREAKING CHANGE:
`format` option is no longer supported as everything is `dag-pb` all of the time.
Follows on from https://github.com/ipfs/js-ipfs-mfs/pull/69
>  feat: removes format option

- package.json
- src/add/index.js
- src/files/cp.js
- src/files/mkdir.js
- src/files/mv.js
- src/files/rm.js
- src/files/write.js
- test/interface.spec.js
> test: adds tests for metadata with mfs stat and files.add
